// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using volvo.DBC.EFCoreSqlite;

#nullable disable

namespace volvo.Server.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20220313234404_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("volvo.Shared.ModelVehicleShared", b =>
                {
                    b.Property<long>("IdModelVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameModelVehicle")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("IdModelVehicle");

                    b.HasIndex("IdModelVehicle");

                    b.ToTable("ModelVehicle");

                    b.HasData(
                        new
                        {
                            IdModelVehicle = 1L,
                            NameModelVehicle = "FH"
                        },
                        new
                        {
                            IdModelVehicle = 2L,
                            NameModelVehicle = "FM"
                        });
                });

            modelBuilder.Entity("volvo.Shared.VehicleShared", b =>
                {
                    b.Property<long>("IdVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdModelVehicle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearManufacturing")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearModel")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.HasKey("IdVehicle");

                    b.HasIndex("IdModelVehicle");

                    b.HasIndex("IdVehicle", "IdModelVehicle");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            IdVehicle = 1L,
                            IdModelVehicle = 1L,
                            YearManufacturing = 2022,
                            YearModel = 2022
                        },
                        new
                        {
                            IdVehicle = 2L,
                            IdModelVehicle = 2L,
                            YearManufacturing = 2022,
                            YearModel = 2023
                        });
                });

            modelBuilder.Entity("volvo.Shared.VehicleShared", b =>
                {
                    b.HasOne("volvo.Shared.ModelVehicleShared", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("IdModelVehicle")
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("volvo.Shared.ModelVehicleShared", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
